export const GET_USERS_START="GET_USERS_START"
export const GET_USERS_SUCCESS="GET_USERS_SUCCESS"
export const GET_USERS_ERROR="GET_USERS_ERROR"


//createing

export const CREATE_USERS_START = 'CREATE_USERS_START';
export const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS';
export const CREATE_USERS_ERROR = 'CREATE_USERS_ERROR';


//delete

export const DELETE_USERS_START = 'DELETE_USERS_START';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const DELETE_USERS_ERROR = 'DELETE_USERS_ERROR';



//update

export const UPDATE_USERS_START = 'UPDATE_USERS_START';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const UPDATE_USERS_ERROR = 'UPDATE_USERS_ERROR';